name: nightly

on:
  schedule:
    # Schedule equates to 02:05
    - cron: '5 2 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: cache-build-artifacts
      uses: actions/cache@v2
      with:
        path: |
          target
          multisig/target
        key: cargo-bpf-1.7.8-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          cargo-bpf-1.7.8

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install -y libudev-dev
        sh -c "$(curl -sSfL https://release.solana.com/v1.7.8/install)"

    - name: Build on-chain BPF programs
      run: |
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

        # Build all BPF programs in the workspace, including the multisig program,
        # because we will need them later to test Solido.
        cargo build-bpf

    - name: Build CLI client
      run: cargo build --bin solido

    - name: Run Solido integration test against devnet
      run: |
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

        solana-keygen new --no-bip39-passphrase --silent
        solana config set --url https://api.devnet.solana.com

        # Loop airdrop as devnet allows at most 10 SOL at a time.
        for i in {1..4}; do solana airdrop 10.0; sleep 30;  done

        NETWORK='https://api.devnet.solana.com' tests/test_solido.py

    - name: Run Multisig integration test against devnet
      run: |
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

        # We don't need to run keygen/setup again, the private key and state
        # should still be there from the previous run.

        # Loop airdrop as devnet allows at most 10 SOL at a time.
        for i in {1..4}; do sleep 30; solana airdrop 10.0;  done

        NETWORK='https://api.devnet.solana.com' tests/test_multisig.py

