[workspace]
members = [
    "cli",
    "multisig/programs/multisig",
    "program",
]

# Ensure that we don't leave half a program running if something in a thread panics.
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
